name: "[Staging] Chromatic (manual)"
on: [push]
# do not use pull_request here, it report the wrong commit_sha and commit_ref

jobs:
  chromatic:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - uses: actions/checkout@v1
    - name: install
      run: yarn && git status --porcelain
    - name: prep package
      run: ./scripts/rename.js storybook-chromatic
    - name: run chromatic
      run: yarn chromatic --only-changed
      env: 
        CHROMATIC_PROJECT_TOKEN: 253df72b53d2
        CHROMATIC_INDEX_URL: https://www.staging-chromatic.com
