name: Release

on:
  # PRs have their own canary releases which always run but don't publish the GitHub Action.
  # Types are configured so this also runs when labels are added or removed.
  # To allow debugging the release process, this does not have a paths filter.
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]

  # Pushes to main trigger a release and publish the GitHub Action. To allow the occasional update
  # to markdown and config files, only changes to actual source code trigger a release.
  push:
    branches:
      - main
    paths:
      - action-src/**
      - bin-src/**
      - node-src/**
      - action.yml
      - isChromatic.*
      - package.json
      - storybook-addon.*

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Prepare repository
        run: git fetch --unshallow --tags
      - run: corepack enable
      - name: Install dependencies
        run: yarn install --immutable

      - name: Create Release
        run: yarn run release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
