name: Release

on:
  # PRs have their own canary releases which always run but don't publish the GitHub Action.
  # To allow debugging the release process, this does not have a paths filter.
  pull_request:
    branches:
      - main

  # Pushes to main trigger a release and publish the GitHub Action. To allow the occasional update
  # to markdown and config files, only changes to actual source code trigger a release.
  push:
    branches:
      - main
    paths:
      - action-src/**
      - bin-src/**
      - node-src/**
      - action.yml
      - isChromatic.*
      - package.json
      - storybook-addon.*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Prepare repository
        run: git fetch --unshallow --tags

      - name: Install dependencies
        run: yarn install --ignore-scripts

      - name: Create Release
        run: yarn run release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
