name: Smoke test via npx
on: push

jobs:
  chromatic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: install
        run: yarn && git status --porcelain
      - name: prep package
        run: ./scripts/rename.js storybook-chromatic
      - run: yarn build
      - name: run chromatic
        run: npx -p . chromatic --build-script-name build-test-storybook --exit-zero-on-changes --force-rebuild
        env:
          LOG_LEVEL: debug
          DEBUG: chromatic-cli
          CHROMATIC_PROJECT_TOKEN: 47c20821d2c2
